# Generated by Django 4.1.3 on 2022-12-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_alter_assessment_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="point",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
