# Generated by Django 4.1.3 on 2022-12-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0001_initial"),
        ("turistics_points", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="turisticpoint",
            name="equipments",
            field=models.ManyToManyField(
                related_name="Turistic_Point", to="equipments.equipment"
            ),
        ),
    ]
