# Generated by Django 4.1.3 on 2022-12-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("turistics_points", "0002_turisticpoint_equipments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turisticpoint",
            name="city",
        ),
        migrations.RemoveField(
            model_name="turisticpoint",
            name="state",
        ),
    ]
