# Generated by Django 4.1.3 on 2022-12-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0001_initial"),
        ("comments", "0001_initial"),
        (
            "turistics_points",
            "0003_remove_turisticpoint_city_remove_turisticpoint_state",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="turisticpoint",
            name="comments",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Turistic_Point",
                to="comments.comment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="turisticpoint",
            name="equipments",
            field=models.ManyToManyField(
                blank=True, related_name="Turistic_Point", to="equipments.equipment"
            ),
        ),
    ]
