# Generated by Django 4.1.3 on 2022-12-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("localizations", "0001_initial"),
        ("turistics_points", "0004_turisticpoint_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turisticpoint",
            name="localizations",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Turustuc_Points",
                to="localizations.localization",
            ),
            preserve_default=False,
        ),
    ]
