# Generated by Django 4.1.3 on 2022-12-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
        ("turistics_points", "0006_alter_turisticpoint_localizations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turisticpoint",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Turistic_Point",
                to="comments.comment",
            ),
        ),
    ]
