# Generated by Django 4.1.3 on 2022-12-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turistics_points", "0007_alter_turisticpoint_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="turisticpoint",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="point_turistic"),
        ),
    ]
