# Generated by Django 4.1.3 on 2022-12-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("opening_hours", models.TextField()),
                ("approval", models.BooleanField(default=True)),
                ("minimun_age", models.IntegerField()),
            ],
        ),
    ]
